CREATE DATABASE globe;
USE globe;
CREATE TABLE country(country_name varchar(30),country_population bigint,country_states int,country_capital varchar(5),country_teritoris int,country_malls bigint,country_tradition varchar(10),coutry_languages varchar(40),country_cities int,country_agriculture double);
DESC country;
USE globe;
CREATE TABLE oceans(ocean_name varchar(50),ocean_no int,ocean_largest_rivr varchar(70),ocean_rivers_merged bigint,ocean_aqualife bigint,ocean_largest_aqualife varchar(40),ocean_ships int,ocean_water_qantity double,ocean_beaaches bigint,ocean_number int);
DESC oceans;
CREATE TABLE continents(continent_name varchar(10),continent_no int,continent_larger_one varchar(10),content_type varchar(30),continent_lives bigint,continent_area bigint,continent_width double,continent_feaatures varchar(50),continent_atmosphere varchar(40),continent_countries_no int);
DESC continents;
CREATE TABLE government(government_name varchar(30),government_type varchar(60),goverment_head varchar(32),government_sectors int,government_funds bigint,government_budjet bigint,government_employees bigint,goverment_meetings int,government_parties int,government_companies bigint);
CREATE TABLE eletric_subtances(eletric_type varchar(20),eletricity_name varchar(20),eletric_stations bigint,eletric_properties int,eletrician_no bigint,eletric_station_id int,eletricc_poles bigint,eletric_nature varchar(10),eletric_connection_number bigint,eletric_switches bigint);
CREATE TABLE education_system(education_type varchar(20),education_level int,education_related_jobs varchar(50),educated_people bigint,non_educated_people bigint,education_minister varchar(30),education_percentage double,education_standards varchar(70),education_noof_teachers int,education_board_types int);
CREATE TABLE movies(movie_name varchar(10),movie_budget bigint,movie_talk varchar(60),movie_release_date varchar(30),movie_noof_crew int,movie_hero varchar(20),movie_heroine varchar(40),movie_noof_theaters int,movie_noof_audience bigint,movie_special_charecter varchar(80));
CREATE TABLE grains_info(grains_name varchar(10),grains_type varchar(40),gains_weight int,grains_price int,grains_produce varchar(60),grains_season varchar(50),grains_calories bigint,grains_carbohydrates bigint,grains_type_popular varchar(40),grains_produce_percentage double,grains_value int);
CREATE TABLE brands_info(brand_name varchar(90),brand_types int,brand_price int,drand_value varchar(30),brand_place varchar(50),brand_ambassador varchar(20),brand_qualatiy double,brand_headquaters varchar(50),brand_noof_products bigint,brand_product_sales int);
CREATE TABLE city_info(city_name varchar(20),city_noof_cities int,city_famous varchar(50),city_noof_streets int,city_noof_companies int,city_signals bigint,city_tourist_places int,city_head varchar(40),city_noof_population bigint,city_noof_city_buses bigint);
DESC city_info;
ALTER TABLE country ADD COLUMN country_id int;
ALTER TABLE country ADD COLUMN country_code varchar(20);
ALTER TABLE country ADD COLUMN country_area double;
ALTER TABLE country ADD COLUMN country_currency varchar(48);
ALTER TABLE country ADD COLUMN country_region varchar(10);
ALTER TABLE country ADD COLUMN country_time_zone varchar(56);
ALTER TABLE country ADD COLUMN country_gdp int;
ALTER TABLE country ADD COLUMN country_independence_date int;
ALTER TABLE country ADD COLUMN country_president varchar(47);
ALTER TABLE country ADD COLUMN country_flag_colour varchar(72);
SELECT * FROM country;
DESC country;
ALTER TABLE country DROP COLUMN country_gdp;
ALTER TABLE country DROP COLUMN country_population;
ALTER TABLE country MODIFY COLUMN country_time_zone int;
ALTER TABLE country MODIFY COLUMN country_area float;
ALTER TABLE country MODIFY COLUMN country_code int;
ALTER TABLE country RENAME COLUMN country_agriculture TO country_farming;
ALTER TABLE country RENAME COLUMN country_code TO country_pin;
ALTER TABLE country RENAME COLUMN country_time_zone TO country_latitude;
ALTER TABLE country RENAME COLUMN country_region TO country_place;
ALTER TABLE country RENAME COLUMN country_currency TO country_economy;
ALTER TABLE oceans ADD COLUMN ocean_id int;
ALTER TABLE oceans ADD COLUMN ocean_surface_area varchar(20);
ALTER TABLE oceans ADD COLUMN ocean_average_depth float;
ALTER TABLE oceans ADD COLUMN ocean_marine_life varchar(63);
ALTER TABLE oceans ADD COLUMN ocean_salinity float;
ALTER TABLE oceans ADD COLUMN ocean_tectonic_plate varchar(84);
ALTER  TABLE oceans ADD COLUMN ocean_geological_features varchar(23);
ALTER TABLE oceans ADD COLUMN ocean_shipping_routes varchar(54);
ALTER TABLE oceans ADD COLUMN ocean_last_updated int;
ALTER TABLE oceans ADD COLUMN ocean_sourroundings_countries varchar(78);
SELECT * FROM oceans;
ALTER TABLE oceans DROP COLUMN ocean_no;
ALTER TABLE oceans DROP COLUMN ocean_id;
ALTER TABLE oceans MODIFY COLUMN ocean_salinity int;
ALTER TABLE oceans MODIFY COLUMN ocean_beaches float;
ALTER TABLE oceans MODIFY COLUMN ocean_last_updated double;
ALTER TABLE oceans RENAME COLUMN ocean_geological_features TO ocean_environment;
ALTER TABLE oceans RENAME COLUMN ocean_surrounding_countries TO ocean_country_name;
ALTER TABLE oceans RENAME COLUMN ocean_shipping_routes TO ocean_water_routes;
ALTER TABLE oceans RENAME COLUMN ocean_last_updated TO ocean_current_updated;
ALTER TABLE oceans RENAME COLUMN ocean_marine_life TO ocean_water_life;
DESC oceans;
ALTER TABLE government ADD COLUMN government_id int;
ALTER TABLE government ADD COLUMN goverment_country_id int;
ALTER TABLE government ADD COLUMN head_of_governmnt int;
ALTER TABLE government ADD COLUMN government_capital_city varchar(54);
ALTER TABLE government ADD COLUMN government_founding_date int;
ALTER TABLE government ADD COLUMN government_construction varchar(34);
ALTER TABLE government ADD COLUMN goverment_legistative_branch varchar(76);
ALTER TABLE government ADD COLUMN government_elections varchar(84);
ALTER TABLE government ADD  COLUMN government_last_updated int;
ALTER TABLE government ADD COLUMN government_term_duration int;
SELECT * FROM government;
ALTER TABLE government DROP COLUMN goverment_head;
ALTER TABLE government DROP COLUMN government_budjet;
ALTER TABLE government MODIFY COLUMN goverment_country_id float;
ALTER TABLE government MODIFY COLUMN goverment_term_duration double;
ALTER TABLE government MODIFY COLUMN goverment_last_updated float;
ALTER TABLE government RENAME COLUMN government_country_id TO country_id;
ALTER TABLE government RENAME COLUMN government_term_duration TO trem_duration;
ALTER TABLE government RENAME COLUMN government_last_updated TO last_updated;
ALTER TABLE government RENAME COLUMN government_parties TO rural_parties;
ALTER TABLE government RENAME COLUMN government_companies TO industries;
DESC government;
ALTER TABLE eletric_subtances ADD COLUMN eletric_subtances_id int;
ALTER TABLE eletric_subtances ADD COLUMN eletric_subtances_name varchar(90);
ALTER TABLE eletric_subtances ADD COLUMN eletric_conductivity float;
ALTER TABLE eletric_subtances ADD COLUMN eletric_resistivity int;
ALTER TABLE eletric_subtances ADD COLUMN eletric_breakdown_voltage float;
ALTER TABLE eletric_subtances ADD COLUMN eletric_melting_point double;
ALTER TABLE eletric_subtances ADD COLUMN eletric_thermal_counductivity int;
ALTER TABLE eletric_subtances ADD COLUMN eletric_specific_heat float;
ALTER TABLE eletric_subtances ADD COLUMN eletric_chemical_formula varchar(85);
ALTER TABLE eletric_subtances ADD COLUMN eletric_magnetic_properties varchar(334);
SELECT * FROM eletric_subtances;
ALTER TABLE eletric_subtances DROP COLUMN eletric_conductivity;
ALTER TABLE eletric_subtances DROP COLUMN eletric_resistivity;
ALTER TABLE eletric_subtances MODIFY COLUMN eletric_specific_heat int;
ALTER TABLE eletric_subtances MODIFY COLUMN eletric_melting_point float;
ALTER TABLE eletric_subtances MODIFY COLUMN eletric_subtances_id bigint;
ALTER TABLE eletric_subtances RENAME COLUMN eletric_properties TO eletric_materials;
ALTER TABLE eletric_subtances RENAME COLUMN eletric_nature TO eletric_ecosystem;
ALTER TABLE eletric_subtances RENAME COLUMN eletric_melting_point TO eletric_melting_stage;
ALTER TABLE eletric_subtances RENAME COLUMN eletric_specific_heat TO eletric_speciific_temparature;
ALTER TABLE eletric_subtances RENAME COLUMN eletric_switches TO eletric_routers;
DESC eletric_subtances;
ALTER TABLE education_system ADD COLUMN system_id int;
ALTER TABLE education_system ADD COLUMN country_id int;
ALTER TABLE education_system ADD COLUMN official_language varchar(80);
ALTER TABLE education_system ADD COLUMN curriculam varchar(34);
ALTER TABLE education_system ADD COLUMN grading_scale varchar(76);
ALTER TABLE education_system ADD COLUMN acadamic_calender varchar(75);
ALTER TABLE education_system ADD COLUMN school_type varchar(80);
ALTER TABLE education_system ADD COLUMN last_updated int;
ALTER TABLE education_system ADD COLUMN contact_information varchar(40);
ALTER TABLE education_system ADD COLUMN notable_institutions varchar(30);
ALTER TABLE education_system ADD COLUMN education_reform varchar(60);
ALTER TABLE education_system ADD COLUMN  school_board varchar(35);
SELECT * FROM education_system;
ALTER TABLE education_system DROP COLUMN school_board;
ALTER TABLE education_system DROP COLUMN system_id;
ALTER TABLE education_system MODIFY COLUMN last_updated double;
ALTER TABLE education_system MODIFY COLUMN country_id float;
ALTER TABLE education_system MODIFY COLUMN school_type double;
ALTER TABLE education_system RENAME COLUMN school_type TO school_category;
ALTER TABLE education_system RENAME COLUMN grading_scale TO marks_state;
ALTER TABLE education_system RENAME COLUMN last_updated TO current_updated;
ALTER TABLE education_system RENAME COLUMN education_reform TO education_application;
ALTER TABLE education_system RENAME COLUMN contact_information TO contact_number;
DESC education_system;
ALTER TABLE movies ADD COLUMN movie_id int;
ALTER TABLE movies ADD COLUMN title varchar(30);
ALTER TABLE movies ADD COLUMN release_year int;
ALTER TABLE movies ADD COLUMN genre varchar(76);
ALTER TABLE movies ADD COLUMN duration_minutes int;
ALTER TABLE movies ADD COLUMN language varchar(87);
ALTER TABLE movies ADD COLUMN rating varchar(20);
ALTER TABLE movies ADD COLUMN plot_summary varchar(80);
ALTER TABLE movies ADD COLUMN box_office int;
ALTER TABLE movies ADD COLUMN trailer_url varchar(75);
SELECT * FROM movies;
ALTER TABLE movies DROP COLUMN movie_id;
ALTER TABLE movies DROP COLUMN title;
ALTER TABLE movies MODIFY COLUMN box_office float;
ALTER TABLE movies MODIFY COLUMN release_year bigint;
ALTER TABLE movies MODIFY COLUMN duration_minutes double;
ALTER TABLE movies RENAME COLUMN box_office To production_house;
ALTER TABLE movies RENAME COLUMN release_year To updated_year;
ALTER TABLE movies RENAME COLUMN plot_summary To plot_story;
ALTER TABLE movies RENAME COLUMN trailer_url To teaser;
ALTER TABLE movies RENAME COLUMN box_office To production_house;
DESC movies;
ALTER TABLE continents ADD COLUMN area varchar(76);
ALTER TABLE continents ADD COLUMN lrgest_country varchar(20);
ALTER TABLE continents ADD COLUMN capital_city varchar(70);
ALTER TABLE continents ADD COLUMN currency varchar(43);
ALTER TABLE continents ADD COLUMN  gdp int;
ALTER TABLE continents ADD COLUMN highest_point varchar(50);
ALTER TABLE continents ADD COLUMN climate varchar(83);
ALTER TABLE continents ADD COLUMN time_zone varchar(30);
ALTER TABLE continents ADD COLUMN current_updated int;
ALTER TABLE continents ADD COLUMN noof_continents int;
SELECT * FROM continents;
ALTER TABLE continents DROP COLUMN area;
ALTER TABLE continents DROP COLUMN gdp;
ALTER TABLE continents MODIFY COLUMN current_updated float;
ALTER TABLE continents MODIFY COLUMN currency float;
ALTER TABLE continents MODIFY COLUMN noof_continents double;
ALTER TABLE continents RENAME COLUMN current_updated TO past_updated;
ALTER TABLE continents RENAME COLUMN currency TO profit;
ALTER TABLE continents RENAME COLUMN noof_continents TO capacity;
ALTER TABLE continents RENAME COLUMN highest_point TO lowest_point;
ALTER TABLE continents RENAME COLUMN climate TO weather;
DESC continents;
ALTER TABLE city_info ADD COLUMN city_id int;
ALTER TABLE city_info ADD COLUMN contry_id int;
ALTER TABLE city_info ADD COLUMN area double;
ALTER TABLE city_info ADD COLUMN time_zone varchar(76);
ALTER TABLE city_info ADD COLUMN latitude float;
ALTER TABLE city_info ADD COLUMN longitude int;
ALTER TABLE city_info ADD COLUMN country varchar(52);
ALTER TABLE city_info ADD COLUMN  mayor varchar(57);
ALTER TABLE city_info ADD COLUMN postal_code int;
ALTER TABLE city_info ADD COLUMN area_code int;
SELECT * FROM city_info;
ALTER TABLE city_info DROP COLUMN area_code;
ALTER TABLE city_info DROP COLUMN mayor;
ALTER TABLE city_info MODIFY COLUMN postal_code float;
ALTER TABLE city_info MODIFY COLUMN longitude double;
ALTER TABLE city_info MODIFY COLUMN area float;
ALTER TABLE city_info RENAME COLUMN area TO location;
ALTER TABLE city_info RENAME COLUMN postal_code TO postal_pin;
ALTER TABLE city_info RENAME COLUMN city_id TO city_pin;
ALTER TABLE city_info RENAME COLUMN time_zone TO time_area;
ALTER TABLE city_info RENAME COLUMN country TO capital;
DESC city_info;
ALTER TABLE brands_info ADD COLUMN brand_id int;
ALTER TABLE brands_info ADD COLUMN category varchar(40);
ALTER TABLE brands_info ADD COLUMN founding_year int;
ALTER TABLE brands_info ADD COLUMN website varchar(60);
ALTER TABLE brands_info ADD COLUMN description_brand varchar(63);
ALTER TABLE brands_info ADD COLUMN slogan varchar(70);
ALTER TABLE brands_info ADD COLUMN logo_url varchar(75);
ALTER TABLE brands_info ADD COLUMN ranking int;
ALTER TABLE brands_info ADD COLUMN awards varchar(40);
ALTER TABLE brands_info ADD COLUMN last_updated int;
SELECT * FROM brands_info;
ALTER TABLE brands_info DROP COLUMN ranking;
ALTER TABLE brands_info DROP COLUMN awards;
ALTER TABLE brands_info MODIFY COLUMN founding_year float;
ALTER TABLE brands_info MODIFY COLUMN brand_id double;
ALTER TABLE brands_info MODIFY COLUMN category float;
ALTER TABLE brands_info RENAME COLUMN founding_year TO updated_year;
ALTER TABLE brands_info RENAME COLUMN category TO group_no;
ALTER TABLE brands_info RENAME COLUMN website TO app;
ALTER TABLE brands_info RENAME COLUMN slogan TO motto;
ALTER TABLE brands_info RENAME COLUMN last_updated TO current_updated;
DESC brands_info;
ALTER TABLE grains_info ADD COLUMN grain_id int;
ALTER TABLE grains_info ADD COLUMN scitific_name varchar(80);
ALTER TABLE grains_info ADD COLUMN family varchar(60);
ALTER TABLE grains_info ADD COLUMN origin varchar(50);
ALTER TABLE grains_info ADD COLUMN cultivation_method varchar(70);
ALTER TABLE grains_info ADD COLUMN nutritional_value varchar(20);
ALTER TABLE grains_info ADD COLUMN culinary_use varchar(10);
ALTER TABLE grains_info ADD COLUMN cooking_method varchar(40);
ALTER TABLE grains_info ADD COLUMN gluten_content varchar(30);
ALTER TABLE grains_info ADD COLUMN physical_properties varchar(10);
SELECT * FROM grains_info;
ALTER TABLE grains_info DROP COLUMN grain_id;
ALTER TABLE grains_info DROP COLUMN cooking_method;
ALTER TABLE grains_info MODIFY COLUMN physical_properties boolean;
ALTER TABLE grains_info MODIFY COLUMN family int;
ALTER TABLE grains_info MODIFY COLUMN nutritional_value float;
ALTER TABLE grains_info RENAME COLUMN nutritional_value TO vitamins;
ALTER TABLE grains_info RENAME COLUMN cultivation_method TO farming_method;
ALTER TABLE grains_info RENAME COLUMN physical_properties TO mental_properties;
ALTER TABLE grains_info RENAME COLUMN family TO generation;
ALTER TABLE grains_info RENAME COLUMN gluten_content TO glucose;
DESC grains_info;
INSERT INTO country VALUES('India',29,7000,'telugu',15,'drovpathi');
INSERT INTO country VALUES('pakistan',40,700,'urdu',14,'binladin');
INSERT INTO country VALUES('bangla_desh',12,27000,'hindi',14,'babar');
INSERT INTO country VALUES('USA',50,56000,'english',224,'bidan');
INSERT INTO country VALUES('russia',48,39000,'russia_lang',22,'puttin');
INSERT INTO country VALUES('africa',56,8000,'affrica_lang',26,'cyril');
INSERT INTO country VALUES('nigeria',40,1500,'hausa',12,'tinibu');
INSERT INTO country VALUES('kenya',10,1000,'swahili',28,'hsien');
INSERT INTO country VALUES('australia',27,21000,'english',01,'albanese');
INSERT INTO country VALUES('canada',25,8900,'french',03,'trudeaue');
INSERT INTO country VALUES('germany',11,4500,'german',09,'walter');
INSERT INTO country VALUES('chaina',30,9000,'mandarin',21,'jinping');
INSERT INTO country VALUES('afganistan',16,78356,'dari',18,'daoud_khan');
INSERT INTO country VALUES('belgium',56,34500,'flemish',23,'michel');
INSERT INTO country VALUES('argentina',18,7800,'spanish',05,'alberto');
INSERT INTO country VALUES('france',20,56700,'french',15,'macron');
INSERT INTO country VALUES('britan',39,96400,'english',15,'rishi_sunak');
INSERT INTO country VALUES('brazil',20,45600,'portuguese',10,'lulanda_shilva');
INSERT INTO country VALUES('algeria',17,7800,'arabic',07,'abdelmadjid');
INSERT INTO country VALUES('greece',25,23400,'greek',08,'sakellaropoulou');
INSERT INTO country VALUES('colombia',14,700,'spanish',19,'gustavo_petro');
INSERT INTO country VALUES('nepal',19,7000,'devanagari',30,'puspa_kamal');
SELECT * FROM country;
SELECT * FROM  country WHERE country_name='India';
SELECT * FROM  country WHERE country_states=27;
SELECT * FROM  country WHERE country_malls=7000;
INSERT INTO brands_info VALUES('MAX',1,2000,'great','mumbai','ram',60.00,'chennai',10000,500,1,2021.6,'htttp/brand','pure_cotton','expand_brand','paris',2016,5,'flipcart');
INSERT INTO brands_info VALUES('apple',2,25000,'great','banglore','sharukh_khan',90.00,'america',1000,50,2,2012,'htttp/apple','technology','know_world','PNGwing',2023,20,'amazon');
INSERT INTO brands_info VALUES('nike',3,1500,'not_bad','hyderabad','cristiano',85.00,'britan',100000,20500,3,2014,'htttp/nike','comfortable','gain_trust','nike',2017,19,'meesho');
INSERT INTO brands_info VALUES('puma',4,20000,'good','chennai','anushka_sharma',70.00,'londan',100500,28500,4,2018,'htttp/puma','all_types','easy_shopping','puma',2013,15,'mintra');
INSERT INTO brands_info VALUES('adidas',5,20600,'not_bad','kerala','ranveer',83.00,'usa',150000,15000,5,2019,'htttp/adidas','sports','provide_sports_material','adidas',2022,30,'ajio');
INSERT INTO brands_info VALUES('coco_cola',6,2000,'bad','jaipur','ranbir',50.00,'arebia',16000,600,6,2021,'htttp/cococola','drinks','business','cococola',2021,40,'bigbazar');
INSERT INTO brands_info VALUES('MAX',1,2000,'great','mumbai','ram',60.00,'chennai',10000,500,1,2021.6,'htttp/brand','pure_cotton','expand_brand','paris',2016,5,'flipcart');
INSERT INTO brands_info VALUES('MAX',1,2000,'great','mumbai','ram',60.00,'chennai',10000,500,1,2021.6,'htttp/brand','pure_cotton','expand_brand','paris',2016,5,'flipcart');